# Numpy

Numpy is an open source python library, that is used in every field of science and enginerring...The numpy library contains a multidimensional array and data structures. Numpy can be used to perform a wide varity of mathematical operations. Numpy was created in 2005.The array object in numpy is called ndarray which is 50x faster than python list.

Arrays are frequently used in data science.We can install numpy through 

pip install numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
print(arr)

[1 2 3 4]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr = np.array((4,5,6,7))

In [6]:
print(arr)
print(type(arr))

[4 5 6 7]
<class 'numpy.ndarray'>


# Dimensions of ndarray

## 0D array

In [7]:
arr = np.array(3)
print(arr)
print(type(arr))

3
<class 'numpy.ndarray'>


In [8]:
print(arr.ndim)

0


## if array contain only one value in it it is called 0D array

## 1D array

In [9]:
arr = np.array([1,2,3,4])
print(arr.ndim)

1


### ndim is used to check dimension of array

## 2D array

In [10]:
arr = np.array([[12,3,4,5],[34,5,7,6]])

In [11]:
print(arr.ndim)

2


In [12]:
print(arr)

[[12  3  4  5]
 [34  5  7  6]]


### Let's check with different things

In [13]:
arr = np.array([[2,3,4,5],[5,6,7]])

C:\Users\Mansoor\AppData\Local\Temp\ipykernel_3384\4165038979.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[2,3,4,5],[5,6,7]])


In [14]:
print(arr)

[list([2, 3, 4, 5]) list([5, 6, 7])]


#### we see that if values are differnt it is not considering as array

In [15]:
print(arr.ndim)

1


### Let's check for different dtypes

In [16]:
arr = np.array([[1,2,3.4],[4,5,6]])

In [17]:
print(arr)

[[1.  2.  3.4]
 [4.  5.  6. ]]


In [18]:
print(arr.ndim)

2


# 3D array

### Let's see some tips to understand 3d array when it comes to 2d array we saw that each sq bracket contain 1d array and 2 sq brackets are used....So for 3d array 3 brackets are used and each contain 2d array

In [19]:
arr = np.array([[[1,2,3,4],[4,3,21,2]],
             [[5,4,32,1],[3,4,5,6]]])

In [20]:
print(arr)

[[[ 1  2  3  4]
  [ 4  3 21  2]]

 [[ 5  4 32  1]
  [ 3  4  5  6]]]


In [21]:
print(arr.ndim)

3


In [22]:
print(arr[1][0][2])

32


In [23]:
print(arr[0][1][2])

21


#### it use a simple concept.. first bracket is for it's portion of 2d array. and remaining use 2d concept

# 4D array

In [24]:
import numpy as np

arr = np.array(
    [
        [
            [
                [1, 29, 35, 44],
                [2, 83, 47, 45]
            ],
            [
                [32, 14, 52, 64],
                [13, 54, 67, 8]
            ]
        ],
        [
            [
                [97, 56, 89, 3],
                [34, 8, 32, 12]
            ],
            [
                [11, 234, 5, 87],
                [867, 45, 34, 22]
            ]
        ]
    ]
)


In [25]:
print(arr[0][0][1][1])

83


In [26]:
print(arr[1][1][0][3])

87


In [27]:
print(arr[1][0][0][3])

3


In [28]:
print(arr.ndim)

4


In [29]:
print(arr)

[[[[  1  29  35  44]
   [  2  83  47  45]]

  [[ 32  14  52  64]
   [ 13  54  67   8]]]


 [[[ 97  56  89   3]
   [ 34   8  32  12]]

  [[ 11 234   5  87]
   [867  45  34  22]]]]


# Higher dimensional array

## we are using ndmin for creating ndimension array....Let's see in action

In [30]:
arr = np.array([1,2,3,4],ndmin=3)

In [31]:
print(f'{arr}\n dimesion of array is {arr.ndim}')

[[[1 2 3 4]]]
 dimesion of array is 3


In [32]:
arr = np.array([23,4,5,3,23,4],ndmin=10)

In [33]:
print(f'{arr}\ndimension of array is {arr.ndim}')

[[[[[[[[[[23  4  5  3 23  4]]]]]]]]]]
dimension of array is 10


# Slicing of np array

## Slicing in 1D array

#### if array is array = [2,3,4,6,7,8,34] print 4,6,7,8 through slicing

In [34]:
array = np.array([2,3,4,6,7,8,34])

In [35]:
print(array[2:6])

[4 6 7 8]


### if array is array = [[2,3,4,5],[7,63,12,65],[8,7,67,5]] print [67,5] 

In [36]:
array = np.array([[2,3,4,5],[7,63,12,65],[8,7,67,5]])

In [37]:
print(array[2][2:4])

[67  5]


## check types of array and create array with dtypes|

In [38]:
arr = np.array([1,2,3,4])

In [39]:
arr.dtype

dtype('int32')

In [40]:
arr = np.array([1,2,34,5,6],dtype='S')

In [41]:
arr.dtype

dtype('S2')

In [43]:
arr = np.array((1,2,3,4),dtype='i4')

In [44]:
arr.dtype

dtype('int32')

#### if we already know about the data type of array we use this

# Numpy array shape

The shape of an array is the number of elements in each dimension

### Print the shape of 2D array

In [46]:
array= np.array([[1,2,3,4],[5,6,7,8]])

In [47]:
array.shape

(2, 4)

In [49]:
array = np.array([[2,3,4],[5,6,7],[7,5,3],[34,56,7]])

In [50]:
array.shape

(4, 3)

# Joining the array

In [51]:
arr = np.array([3,4,5])
arr1 = np.array([6,54,34])

In [53]:
array = np.concatenate((arr,arr1))

In [54]:
array

array([ 3,  4,  5,  6, 54, 34])

### For 2D

In [55]:
arr = np.array([[1,2,3],[4,5,6]])

In [57]:
arr1 = np.array([[4,3,2],[7,56,4]])

In [58]:
array = np.concatenate((arr,arr1))

In [59]:
print(array)

[[ 1  2  3]
 [ 4  5  6]
 [ 4  3  2]
 [ 7 56  4]]


In [60]:
array = np.concatenate((arr,arr1),axis=0)

In [61]:
print(array)

[[ 1  2  3]
 [ 4  5  6]
 [ 4  3  2]
 [ 7 56  4]]


In [62]:
array = np.concatenate((arr,arr1),axis=1)

In [63]:
print(array)

[[ 1  2  3  4  3  2]
 [ 4  5  6  7 56  4]]


### in 2D array by default value of axis is 0 as we already see it in example

# Spliting Values

In [64]:
arr = np.array([1,2,6,7,8])

In [68]:
np.array_split(arr,2)

[array([1, 2, 6]), array([7, 8])]

In [69]:
np.array_split(arr,5)

[array([1]), array([2]), array([6]), array([7]), array([8])]

# Ravel and Flaten functions

These both function has single purpose which is converting multi dimension array into 1D

In [71]:
arr = np.array([1,2,4,5,6],ndmin=3)

In [72]:
print(arr)

[[[1 2 4 5 6]]]


In [73]:
print(arr.ndim)

3


In [77]:
d = arr.ravel()

In [79]:
d

array([1, 2, 4, 5, 6])

In [80]:
d.ndim

1

In [81]:
arr = np.array([5,6,7,42,2],ndmin=2)

In [82]:
d = arr.flatten()

In [83]:
arr.ndim

2

In [84]:
d.ndim

1

# Unique Value Finder

In [85]:
arr = np.array([23,1,3,5,6,34,657,76,53,23,4,4,5,6,657])

In [87]:
np.unique(arr)

array([  1,   3,   4,   5,   6,  23,  34,  53,  76, 657])

### Also return index

In [88]:
np.unique(arr,return_index=True)

(array([  1,   3,   4,   5,   6,  23,  34,  53,  76, 657]),
 array([ 1,  2, 10,  3,  4,  0,  5,  8,  7,  6], dtype=int64))

### Also return columns position

In [89]:
np.unique(arr,return_index=True,return_counts=True)

(array([  1,   3,   4,   5,   6,  23,  34,  53,  76, 657]),
 array([ 1,  2, 10,  3,  4,  0,  5,  8,  7,  6], dtype=int64),
 array([1, 1, 2, 2, 2, 2, 1, 1, 1, 2], dtype=int64))

### Return inverse

In [90]:
np.unique(arr,return_inverse=True)

(array([  1,   3,   4,   5,   6,  23,  34,  53,  76, 657]),
 array([5, 0, 1, 3, 4, 6, 9, 8, 7, 5, 2, 2, 3, 4, 9], dtype=int64))

# Delete

In [91]:
x = np.array([3,4,5,6,7,8])

In [92]:
np.delete(x,[3])

array([3, 4, 5, 7, 8])

In [94]:
np.delete(x,[2])

array([3, 4, 6, 7, 8])

### Same concept we apply in 2D array inwhich we delete row or columns by using axis 

In [95]:
x = np.array([[2,56,7],[6,4,2],[3,4,5]])

In [97]:
np.delete(x,1,axis=0)

array([[ 2, 56,  7],
       [ 3,  4,  5]])

In [98]:
np.delete(x,1,axis=1)

array([[2, 7],
       [6, 2],
       [3, 5]])